### ISSUE TITLE
Release with custom args in vm.args -name not starting after upgrade to 2.10

### ISSUE THREAD

**Issue by lukaszsamson** [bitwalker/distillery#562]
### Steps to reproduce

In vm.args
`-name ${NODE_NAME}@${NODE_IP}`
NODE_NAME and NODE_IP are in process env
REPLACE_OS_VARS is set to true

release fails to start with
`Failed setting -name! The hostname in '@' is not fully qualified`

Works fine in distillery <= 2.9

**Comment by mmrobins** [comment]
I got this error as well in a kubernetes job where I had forgotten to set these environment variables in my yaml.  I had set them in the yaml for my deployment

```
          env:
            -
              name: NODE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
```

But had forgotten to do that in the job yaml.  Before distillery 2.10 it didn't complain about that, but it seems to now, which seems like better behavior to be honest.

Hopefully that's helpful for you or someone else for debugging this kind of error.
